Add Move Files
mate-academy/node_move-files pull request #92
Opened 2023-07-10 15:04 UTC by ruslanpashkov

2023-07-11 12:20 UTC, roman-mirzoian requested changes
The application is well written, but now there are some errors when using it:
1. If you try to rename the file, the application will crash.
![image](https://github.com/mate-academy/node_move-files/assets/54860641/d1b391d9-5137-480f-b5ac-dfe2e6c538bf)
2. If you try to move the file to a non-existent folder, it will be renamed.
![image](https://github.com/mate-academy/node_move-files/assets/54860641/d9be92e3-b0ee-471f-9ca0-f74caed3aca5)
![image](https://github.com/mate-academy/node_move-files/assets/54860641/ae8b5927-faa9-4bbe-80b6-5d10906ba1b0)
3. If you try to move the file to an existing folder, you will receive a message that everything is successful, and then an error will occur.
![image](https://github.com/mate-academy/node_move-files/assets/54860641/d96e6bb8-35d8-4006-84fc-c54ce283d691)

Also, the type of operation (changing the name or moving) should be done at the beginning of the function, so as not to perform unnecessary actions (for example, checking if a folder exists when we only want to change the name).

2023-07-11 12:20 UTC, roman-mirzoian commented on src/app.js
> +  console.log('File moved successfully.');
If we rename the file, but do not move it, this message will not be correct.

2023-07-11 12:20 UTC, roman-mirzoian commented on src/app.js
> +const [source, destination] = process.argv.slice(2);
If we're just renaming the file, then the name `destination` won't quite fit, it's better to call it `param` or something similar to something more general.

2023-07-11 12:20 UTC, roman-mirzoian commented on src/app.js
> +moveFile(source, destination);
It is not necessary to pass these variables as function arguments (`source`, `destination`), they can be defined at the beginning of the file and used directly in the function.

2023-07-11 12:20 UTC, roman-mirzoian commented on src/app.js
> +  const finalDestinationPath = destinationPath.endsWith('/')
In the new path for the file `/` will not necessarily be at the end (see the example in the task), so you need to check if it is there at all.

2023-07-25 10:55 UTC, naziamoff approved these changes
👍

2023-12-12 12:59 UTC, closed without merging